"use client";
import Link from "next/link";
import { useEffect, useState } from "react";
type Tab="questions"|"reviews";
type Item={id:string;text:string;answer:string;readAt:string|null;createdAt:string;rating?:number;images?:string[];isVisible:boolean;authorName?:string;product:{name:string;slug:string};customer?:{name:string;lastName:string}|null};
type State="all"|"new"|"read"|"answered";
const states:{key:State;label:string}[]=[{key:"new",label:"Новые"},{key:"read",label:"Прочитанные"},{key:"answered",label:"Отвеченные"},{key:"all",label:"Все"}];
export function CommunityAdminClient({initialTab="questions",hideTabs=false}:{initialTab?:Tab;hideTabs?:boolean}){
 const [tab,setTab]=useState(initialTab),[state,setState]=useState<State>("new"),[query,setQuery]=useState(""),[search,setSearch]=useState(""),[page,setPage]=useState(1),[revision,setRevision]=useState(0);
 const [items,setItems]=useState<Item[]>([]),[counts,setCounts]=useState<Record<State,number>>({all:0,new:0,read:0,answered:0}),[total,setTotal]=useState(0),[loading,setLoading]=useState(true),[error,setError]=useState("");
 useEffect(()=>{setTab(initialTab);setPage(1);},[initialTab]);
 useEffect(()=>{const c=new AbortController();setLoading(true);setError("");fetch(`/api/admin/community?entity=${tab}&state=${state}&search=${encodeURIComponent(search)}&page=${page}`,{cache:"no-store",signal:c.signal}).then(async r=>{const d=await r.json();if(!r.ok)throw Error(d.error);setItems(d[tab]||[]);setCounts(d.counts);setTotal(d.total);}).catch(e=>{if(!c.signal.aborted)setError(e.message||"Не удалось загрузить сообщения.");}).finally(()=>{if(!c.signal.aborted)setLoading(false);});return()=>c.abort();},[tab,state,search,page,revision]);
 async function patch(id:string,data:Record<string,unknown>){if(data.remove){const r=await fetch(`/api/admin/community?entity=${tab==="reviews"?"review":"question"}&id=${encodeURIComponent(id)}`,{method:"DELETE"});const d=await r.json();if(!r.ok)throw Error(d.error);setRevision(n=>n+1);return;}const r=await fetch("/api/admin/community",{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({entity:tab==="reviews"?"review":"question",id,...data})});const d=await r.json();if(!r.ok)throw Error(d.error);setRevision(n=>n+1);}
 return <div><div className="admin-panel"><div className="admin-panel-heading">{!hideTabs&&<div className="admin-editor-tabs">{(["questions","reviews"] as const).map(t=><button key={t} aria-pressed={tab===t} onClick={()=>{setTab(t);setPage(1);}}>{t==="questions"?"Вопросы":"Отзывы"}</button>)}</div>}<form className="admin-search-row" onSubmit={e=>{e.preventDefault();setSearch(query);setPage(1);}}><input aria-label="Поиск по товару или бренду" value={query} onChange={e=>setQuery(e.target.value)} placeholder="Товар или бренд"/><button className="admin-secondary-button">Найти</button></form></div><div className="admin-editor-tabs" aria-label="Статус сообщения">{states.map(s=><button key={s.key} aria-pressed={state===s.key} onClick={()=>{setState(s.key);setPage(1);}}>{s.label} <span className="admin-count">{counts[s.key]}</span></button>)}</div></div>
 {error&&<div role="alert" className="admin-alert admin-alert-error">{error} <button onClick={()=>setRevision(n=>n+1)}>Повторить</button></div>}
 {loading?<p className="admin-empty" role="status">Загружаем сообщения…</p>:!error&&items.length===0?<div className="admin-empty">В этом разделе пока нет сообщений.</div>:<div className="admin-message-list">{items.map(item=><MessageCard key={item.id} item={item} patch={data=>patch(item.id,data)} />)}</div>}
 {total>30&&<div className="admin-search-row"><button className="admin-secondary-button" disabled={page===1} onClick={()=>setPage(n=>n-1)}>Назад</button><span>{page} / {Math.ceil(total/30)}</span><button className="admin-secondary-button" disabled={page*30>=total} onClick={()=>setPage(n=>n+1)}>Далее</button></div>}</div>;
}
function MessageCard({item,patch}:{item:Item;patch:(data:Record<string,unknown>)=>Promise<void>}){
 const [answer,setAnswer]=useState(item.answer||""),[busy,setBusy]=useState(false),[error,setError]=useState("");
 async function save(data:Record<string,unknown>){setBusy(true);setError("");try{await patch(data);}catch(e){setError(e instanceof Error?e.message:"Нет связи с сервером.");}finally{setBusy(false);}}
 return <article className="admin-panel"><div className="admin-panel-heading"><div><Link href={`/product/${encodeURIComponent(item.product.slug)}`} target="_blank"><strong>{item.product.name}</strong></Link><p className="admin-muted">{item.customer?[item.customer.name,item.customer.lastName].filter(Boolean).join(" "):item.authorName||"Покупатель"} · {new Date(item.createdAt).toLocaleString("ru-RU")}{item.rating?` · ${item.rating} / 5`:""}</p></div><span className="admin-status-pill">{item.answer?"Отвечено":item.readAt?"Прочитано":"Новое"}</span></div><p className="admin-message-text">{item.text}</p>{item.images?.length? <div className="admin-message-images">{item.images.map((src,i)=><a key={i} href={src} target="_blank" rel="noreferrer"><img src={src} alt={`Фото к отзыву ${i+1}`} width="100" height="100"/></a>)}</div>:null}
 <form onSubmit={e=>{e.preventDefault();void save({answer});}}><label className="admin-field"><span>Ответ магазина</span><textarea rows={3} maxLength={5000} value={answer} onChange={e=>setAnswer(e.target.value)} placeholder="Напишите ответ покупателю"/></label><div className="admin-search-row"><button disabled={busy||!answer.trim()} className="admin-primary-button">{busy?"Сохраняем…":item.answer?"Сохранить ответ":"Ответить"}</button><button type="button" disabled={busy} className="admin-secondary-button" onClick={()=>void save({read:!item.readAt})}>{item.readAt?"Отметить непрочитанным":"Отметить прочитанным"}</button><button type="button" disabled={busy} className="admin-secondary-button" onClick={()=>void save({isVisible:!item.isVisible})}>{item.isVisible?"Скрыть с сайта":"Опубликовать"}</button><button type="button" disabled={busy} className="admin-secondary-button" onClick={()=>{if(window.confirm("Удалить сообщение без возможности восстановления?"))void save({remove:true});}}>Удалить</button></div>{error&&<p role="alert" className="admin-alert admin-alert-error">{error}</p>}</form></article>;
}
