"use client";
import { useState } from "react";
import { ImageDropZone } from "@/components/admin/image-drop-zone";
import type { DeliverySettings } from "@/lib/delivery-settings";
export function DeliverySettingsForm({initialSettings}:{initialSettings:DeliverySettings}) {
 const [value,setValue]=useState(initialSettings),[pending,setPending]=useState(false),[message,setMessage]=useState("");
 async function save(event:React.FormEvent){event.preventDefault();setPending(true);setMessage("");try{const response=await fetch("/api/admin/delivery-settings",{method:"PUT",headers:{"Content-Type":"application/json"},body:JSON.stringify(value)});const data=await response.json();if(!response.ok)throw Error(data.error);setValue(data.settings);setMessage("Зоны доставки сохранены.");}catch(e){setMessage(e instanceof Error?e.message:"Ошибка сохранения.");}finally{setPending(false);}}
 return <form className="admin-card admin-form-layout" onSubmit={save}><h2>Карта и стоимость доставки</h2><p>Самовывоз бесплатный. Стоимость СДЭК согласовывает оператор. Для курьера добавьте зоны и загрузите карту с их границами; без выбранной зоны стоимость согласует менеджер.</p>
 <ImageDropZone value={value.mapImage} onChange={mapImage=>setValue(v=>({...v,mapImage}))} label="Карта зон доставки"/>
 {value.zones.map((zone,index)=><fieldset key={zone.id} className="admin-card"><legend>Зона {index+1}</legend><div className="admin-form-grid"><label>Название<input required className="admin-input" value={zone.name} onChange={e=>setValue(v=>({...v,zones:v.zones.map(z=>z.id===zone.id?{...z,name:e.target.value}:z)}))}/></label><label>Стоимость, ₽<input required className="admin-input" type="number" min={0} max={1000000} step={1} value={zone.price} onChange={e=>setValue(v=>({...v,zones:v.zones.map(z=>z.id===zone.id?{...z,price:Number(e.target.value)}:z)}))}/></label><label>Районы и условия<input className="admin-input" value={zone.description} onChange={e=>setValue(v=>({...v,zones:v.zones.map(z=>z.id===zone.id?{...z,description:e.target.value}:z)}))}/></label></div><button type="button" className="admin-btn" onClick={()=>setValue(v=>({...v,zones:v.zones.filter(z=>z.id!==zone.id)}))}>Удалить зону</button></fieldset>)}
 <div className="flex flex-wrap gap-3"><button type="button" className="admin-btn" onClick={()=>setValue(v=>({...v,zones:[...v.zones,{id:crypto.randomUUID(),name:"",price:0,description:""}]}))}>Добавить зону</button><button className="admin-btn admin-btn-primary" disabled={pending}>{pending?"Сохраняем…":"Сохранить доставку"}</button></div>{message&&<p role="status">{message}</p>}</form>;
}
