"use client";
import { useRef,useState } from "react";
import { useRouter } from "next/navigation";
type Kind="products"|"variants"|"prices";
type Result={ok?:boolean;applied?:boolean;digest?:string;created?:number;updated?:number;total?:number;error?:string;errors?:string[];preview?:{row:number;key:string;operation:string;changes:Record<string,unknown>}[]};
export function PositionsImportForm(){
 const router=useRouter(),fileRef=useRef<HTMLInputElement>(null);const [kind,setKind]=useState<Kind>("prices"),[result,setResult]=useState<Result|null>(null),[busy,setBusy]=useState(false),[fileName,setFileName]=useState("");
 async function upload(apply=false){const file=fileRef.current?.files?.[0];if(!file){setResult({error:"Выберите таблицу."});return;}setBusy(true);try{const data=new FormData();data.set("file",file);if(apply){data.set("apply","1");data.set("digest",result?.digest||"");}const r=await fetch(`/api/admin/positions/table?kind=${kind}`,{method:"POST",body:data});const d=await r.json();setResult(d);if(d.applied){router.refresh();window.dispatchEvent(new Event("store-settings-updated"));}}catch{setResult({error:"Нет связи с сервером. Проверьте состояние импорта перед повторной загрузкой."});}finally{setBusy(false);}}
 return <section className="admin-panel"><div className="admin-panel-heading"><div><h2>Товары и остатки в таблицах</h2><p className="admin-muted">Скачайте шаблон, заполните его и проверьте изменения перед применением.</p></div></div><div className="admin-editor-tabs">{([{key:"prices",title:"Цены и остатки"},{key:"products",title:"Модели товаров"},{key:"variants",title:"Позиции и варианты"}] as const).map(t=><button type="button" key={t.key} disabled={busy} aria-pressed={kind===t.key} onClick={()=>{setKind(t.key);setResult(null);setFileName("");if(fileRef.current)fileRef.current.value="";}}>{t.title}</button>)}</div><div className="admin-search-row"><a className="admin-secondary-button" href={`/api/admin/positions/table?kind=${kind}&template=1`}>Скачать шаблон</a><a className="admin-secondary-button" href={`/api/admin/positions/table?kind=${kind}`}>Выгрузить текущие данные</a></div><p className="admin-muted">В шаблоне есть инструкция и справочники. Пустые ячейки сохраняют текущие значения. Ничего не удаляется. Для снятия старой цены укажите 0.</p><div className="admin-search-row"><input ref={fileRef} type="file" aria-label="Таблица для загрузки" accept=".xlsx,.xls,.csv" disabled={busy} onChange={e=>{setFileName(e.target.files?.[0]?.name||"");setResult(null);}}/><button type="button" disabled={busy||!fileName} className="admin-primary-button" onClick={()=>void upload()}>{busy?"Проверяем…":"Проверить таблицу"}</button></div>
 {result?.error&&<p role="alert" className="admin-alert admin-alert-error">{result.error}</p>}{result?.errors?.length? <div role="alert" className="admin-alert admin-alert-error"><strong>Исправьте ошибки — данные не изменены.</strong><ul>{result.errors.map((e,i)=><li key={i}>{e}</li>)}</ul></div>:null}
 {result?.ok&&<div className="admin-alert" role="status">{result.applied?"Готово":"Предпросмотр"}: новых — {result.created}, обновлений — {result.updated}. {result.total!>50?"Показаны первые 50 строк.":""}</div>}
 {result?.ok&&!result.applied&&<><div className="admin-table-wrap"><table className="admin-table"><thead><tr><th>Строка</th><th>Артикул / модель</th><th>Действие</th><th>Изменения</th></tr></thead><tbody>{result.preview?.map(row=><tr key={row.row}><td>{row.row}</td><td>{row.key}</td><td>{row.operation==="create"?"Создать":"Обновить"}</td><td>{Object.entries(row.changes).filter(([k])=>!['productId','slug','sku'].includes(k)).map(([k,v])=>`${k}: ${Array.isArray(v)?v.join(', '):v??'—'}`).join(" · ")}</td></tr>)}</tbody></table></div><div className="admin-search-row"><button type="button" disabled={busy} onClick={()=>void upload(true)} className="admin-primary-button">Применить {result.total} строк</button><button type="button" disabled={busy} onClick={()=>setResult(null)} className="admin-secondary-button">Отменить</button></div></>}
 </section>;
}
